version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nodesessiontokendb
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - sessiontokendb:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  sessiontokendb:
