version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nodedb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
        - ./:/var/lib/postgresql/data
